version: '3.1'

services:

  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: db_password

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '80:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: email@address.com
      PGADMIN_DEFAULT_PASSWORD: password